application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images

- url: /javascripts
  static_dir: javascripts
  
- url: /.*
  script: helloapple.app
